files:
  - source: /zh/*.md
    ignore:
      - SUMMARY.md
    translation: '%original_file_name%'
  - source: /zh/events/finished/*.md
    translation: events/finished/%original_file_name%
  - source: /zh/events/ongoing/*.md
    translation: events/ongoing/%original_file_name%
  - source: /zh/contribute/*md
    translation: contribute/%original_file_name%
  - source: /zh/news/*.md
    translation: news/%original_file_name%
  - source: /zh/help/*.md
    translation: help/%original_file_name%
